version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile.develop
    tty: true
    volumes:
      - ./src:/go/household/src
    ports:
      - 8080:80
    env_file: .env
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - TZ=Asia/Tokyo
#    env_file:
#      - .env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    volumes:
      # 永続かするときにマウントするディレクトリ
      - ./mysql/data:/var/lib/mysql
      # 初期データを投入するSQLが格納されているディレクトリ
      - ./mysql/init:/docker-entrypoint-initdb.d